# Generated by Django 2.1.7 on 2019-03-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='blogpagegalleryimage',
            name='image',
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='icon_url',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='blogpagegalleryimage',
            name='url_image',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
