# Generated by Django 2.1.7 on 2019-03-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bapppage',
            name='contentpage_ptr',
        ),
        migrations.RemoveField(
            model_name='bappsector',
            name='page',
        ),
        migrations.RemoveField(
            model_name='bappstep',
            name='page',
        ),
        migrations.RemoveField(
            model_name='bizpagegallerytechnologies',
            name='image',
        ),
        migrations.RemoveField(
            model_name='contentpagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='devpagegallerysite',
            name='image',
        ),
        migrations.RemoveField(
            model_name='devpagegallerytechnologies',
            name='image',
        ),
        migrations.AddField(
            model_name='bizpagegallerytechnologies',
            name='image_url',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='contentpagegalleryimage',
            name='image_url',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='devpagegallerysite',
            name='image_url',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='devpagegallerytechnologies',
            name='image_url',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.DeleteModel(
            name='BAppPage',
        ),
        migrations.DeleteModel(
            name='BAppSector',
        ),
        migrations.DeleteModel(
            name='BAppStep',
        ),
    ]
