# Generated by Django 2.1.7 on 2019-03-15 08:28

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20190315_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='bizapppage',
            name='principle_en',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='bizapppage',
            name='principle_fr',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='bizapppage',
            name='quote_text_en',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='bizapppage',
            name='quote_text_fr',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='bizapppage',
            name='sector_text_en',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='bizapppage',
            name='sector_text_fr',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='bizapppage',
            name='text_techno_en',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='bizapppage',
            name='text_techno_fr',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='bizappsector',
            name='text_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bizappsector',
            name='text_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bizappsector',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bizappsector',
            name='title_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bizappstep',
            name='text_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bizappstep',
            name='text_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bizappstep',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='bizappstep',
            name='title_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='consultingpage',
            name='text_BPO_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultingpage',
            name='text_BPO_fr',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultingpage',
            name='text_IT_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultingpage',
            name='text_IT_fr',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultingpage',
            name='text_consulting_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultingpage',
            name='text_consulting_fr',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='body_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='body_fr',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='intro_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='intro_fr',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contentpage',
            name='short_description_fr',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contentpagegalleryimage',
            name='caption_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='contentpagegalleryimage',
            name='caption_fr',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='devpage',
            name='text_responsive_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devpage',
            name='text_responsive_fr',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devpage',
            name='text_techno_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devpage',
            name='text_techno_fr',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devpagegallerysite',
            name='caption_en',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='devpagegallerysite',
            name='caption_fr',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=450, null=True),
        ),
        migrations.AddField(
            model_name='domainpage',
            name='intro_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domainpage',
            name='intro_fr',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='intro_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='intro_fr',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='subject_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='subject_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='thank_you_text_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formpage',
            name='thank_you_text_fr',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
